image:
  file: .gitpod.Dockerfile


tasks:
  - name: Shadow-cljs - set devtools-url to fix WS connection to go through the host that GitPod exposes it as
    # GitPod exposes each port under `https://<port>-<workspace url>:443` so we need to tell Shadow to connect to WebSockets via that:
    # (alternatively, the user could install https://www.gitpod.io/blog/local-app to be able to use the VM via localhost)
    # See https://github.com/gitpod-io/gitpod/issues/3282 for background and https://shadow-cljs.github.io/docs/UsersGuide.html#proxy-support
    command: export URL="$(echo $GITPOD_WORKSPACE_URL | sed 's/https:\/\//9630-/')"; sed -i "s/;GITPOD_REPLACE/:devtools-url \"https:\/\/$URL\"/" front-clj/ursula/shadow-cljs.edn

vscode:
  extensions:
    - betterthantomorrow.calva
    - borkdude.clj-kondo
    - oven.bun-vscode
